export interface BranchThemeDefinition {
  key: string;
  name: string;
  description: string;
  previewClass: string;
  values: Record<string, string>;
}

export const BRANCH_THEMES: BranchThemeDefinition[] = [
  {
    key: 'emerald',
    name: 'Emerald',
    description: 'Default green pharmacy look',
    previewClass: 'from-emerald-600 via-green-500 to-teal-400',
    values: {
      '--body': '#f4fbf7',
      '--navbar': '#fefefe',
      '--navbar-border': '#d1e7dc',
      '--card': '#ffffff',
      '--card-foreground': '#0f172a',
      '--popover': '#ffffff',
      '--popover-foreground': '#0f172a',
      '--primary': '#047857',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ecfdf5',
      '--secondary-foreground': '#14532d',
      '--muted': '#d1fae5',
      '--muted-foreground': '#4b5563',
      '--accent': '#a7f3d0',
      '--accent-foreground': '#065f46',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#d8e7de',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#bbf7d0',
      '--ring': '#047857',
      '--chart-1': '#065f46',
      '--chart-2': '#10b981',
      '--chart-3': '#14b8a6',
      '--chart-4': '#0ea5e9',
      '--chart-5': '#6366f1',
      '--sidebar': '#f7fcf9',
      '--sidebar-foreground': '#0f172a',
      '--sidebar-primary': '#047857',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#ecfdf5',
      '--sidebar-accent-foreground': '#14532d',
      '--sidebar-border': '#d1e7dc',
      '--sidebar-ring': '#047857',
    },
  },
  {
    key: 'ocean',
    name: 'Ocean',
    description: 'Cool blue and cyan surfaces',
    previewClass: 'from-sky-700 via-cyan-500 to-blue-400',
    values: {
      '--body': '#f3f8fd',
      '--navbar': '#fbfdff',
      '--navbar-border': '#d2e4f6',
      '--card': '#ffffff',
      '--card-foreground': '#0f172a',
      '--popover': '#ffffff',
      '--popover-foreground': '#0f172a',
      '--primary': '#0369a1',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0f2fe',
      '--secondary-foreground': '#0c4a6e',
      '--muted': '#dbeafe',
      '--muted-foreground': '#475569',
      '--accent': '#bae6fd',
      '--accent-foreground': '#0c4a6e',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#d8e5f0',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#bfdbfe',
      '--ring': '#0369a1',
      '--chart-1': '#075985',
      '--chart-2': '#0ea5e9',
      '--chart-3': '#06b6d4',
      '--chart-4': '#2563eb',
      '--chart-5': '#7c3aed',
      '--sidebar': '#f5fbff',
      '--sidebar-foreground': '#0f172a',
      '--sidebar-primary': '#0369a1',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#e0f2fe',
      '--sidebar-accent-foreground': '#0c4a6e',
      '--sidebar-border': '#d2e4f6',
      '--sidebar-ring': '#0369a1',
    },
  },
  {
    key: 'sunset',
    name: 'Sunset',
    description: 'Warm coral and orange blend',
    previewClass: 'from-orange-600 via-rose-500 to-amber-400',
    values: {
      '--body': '#fff7f3',
      '--navbar': '#fffdfc',
      '--navbar-border': '#f2ddd4',
      '--card': '#ffffff',
      '--card-foreground': '#1f2937',
      '--popover': '#ffffff',
      '--popover-foreground': '#1f2937',
      '--primary': '#ea580c',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffedd5',
      '--secondary-foreground': '#9a3412',
      '--muted': '#ffe4e6',
      '--muted-foreground': '#6b7280',
      '--accent': '#fed7aa',
      '--accent-foreground': '#9a3412',
      '--destructive': '#dc2626',
      '--destructive-foreground': '#ffffff',
      '--border': '#f2e0d8',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#fdba74',
      '--ring': '#ea580c',
      '--chart-1': '#c2410c',
      '--chart-2': '#f97316',
      '--chart-3': '#fb7185',
      '--chart-4': '#f59e0b',
      '--chart-5': '#8b5cf6',
      '--sidebar': '#fff9f7',
      '--sidebar-foreground': '#1f2937',
      '--sidebar-primary': '#ea580c',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#ffedd5',
      '--sidebar-accent-foreground': '#9a3412',
      '--sidebar-border': '#f2ddd4',
      '--sidebar-ring': '#ea580c',
    },
  },
  {
    key: 'royal',
    name: 'Royal',
    description: 'Deep indigo and violet',
    previewClass: 'from-indigo-700 via-violet-600 to-blue-500',
    values: {
      '--body': '#f6f7ff',
      '--navbar': '#fcfcff',
      '--navbar-border': '#dddff8',
      '--card': '#ffffff',
      '--card-foreground': '#111827',
      '--popover': '#ffffff',
      '--popover-foreground': '#111827',
      '--primary': '#4338ca',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e0e7ff',
      '--secondary-foreground': '#312e81',
      '--muted': '#ede9fe',
      '--muted-foreground': '#4b5563',
      '--accent': '#c7d2fe',
      '--accent-foreground': '#312e81',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#dde2f3',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#c7d2fe',
      '--ring': '#4338ca',
      '--chart-1': '#3730a3',
      '--chart-2': '#6366f1',
      '--chart-3': '#8b5cf6',
      '--chart-4': '#3b82f6',
      '--chart-5': '#06b6d4',
      '--sidebar': '#f8f8ff',
      '--sidebar-foreground': '#111827',
      '--sidebar-primary': '#4338ca',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#e0e7ff',
      '--sidebar-accent-foreground': '#312e81',
      '--sidebar-border': '#dddff8',
      '--sidebar-ring': '#4338ca',
    },
  },
  {
    key: 'rose',
    name: 'Rose',
    description: 'Soft pink with berry contrast',
    previewClass: 'from-rose-600 via-pink-500 to-fuchsia-400',
    values: {
      '--body': '#fff6f8',
      '--navbar': '#fffdfd',
      '--navbar-border': '#f2dce3',
      '--card': '#ffffff',
      '--card-foreground': '#1f2937',
      '--popover': '#ffffff',
      '--popover-foreground': '#1f2937',
      '--primary': '#e11d48',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ffe4e6',
      '--secondary-foreground': '#9f1239',
      '--muted': '#fce7f3',
      '--muted-foreground': '#6b7280',
      '--accent': '#fecdd3',
      '--accent-foreground': '#9f1239',
      '--destructive': '#dc2626',
      '--destructive-foreground': '#ffffff',
      '--border': '#f0dde2',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#f9a8d4',
      '--ring': '#e11d48',
      '--chart-1': '#be123c',
      '--chart-2': '#f43f5e',
      '--chart-3': '#ec4899',
      '--chart-4': '#fb7185',
      '--chart-5': '#8b5cf6',
      '--sidebar': '#fff8fa',
      '--sidebar-foreground': '#1f2937',
      '--sidebar-primary': '#e11d48',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#ffe4e6',
      '--sidebar-accent-foreground': '#9f1239',
      '--sidebar-border': '#f2dce3',
      '--sidebar-ring': '#e11d48',
    },
  },
  {
    key: 'amber',
    name: 'Amber',
    description: 'Golden and honey highlights',
    previewClass: 'from-amber-600 via-yellow-500 to-orange-400',
    values: {
      '--body': '#fffaf0',
      '--navbar': '#fffefb',
      '--navbar-border': '#efe2bf',
      '--card': '#ffffff',
      '--card-foreground': '#1f2937',
      '--popover': '#ffffff',
      '--popover-foreground': '#1f2937',
      '--primary': '#d97706',
      '--primary-foreground': '#ffffff',
      '--secondary': '#fef3c7',
      '--secondary-foreground': '#92400e',
      '--muted': '#fde68a',
      '--muted-foreground': '#6b7280',
      '--accent': '#fcd34d',
      '--accent-foreground': '#92400e',
      '--destructive': '#dc2626',
      '--destructive-foreground': '#ffffff',
      '--border': '#ede0c2',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#fcd34d',
      '--ring': '#d97706',
      '--chart-1': '#b45309',
      '--chart-2': '#f59e0b',
      '--chart-3': '#f97316',
      '--chart-4': '#84cc16',
      '--chart-5': '#14b8a6',
      '--sidebar': '#fffdf6',
      '--sidebar-foreground': '#1f2937',
      '--sidebar-primary': '#d97706',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#fef3c7',
      '--sidebar-accent-foreground': '#92400e',
      '--sidebar-border': '#efe2bf',
      '--sidebar-ring': '#d97706',
    },
  },
  {
    key: 'teal',
    name: 'Teal',
    description: 'Mint and sea-glass tones',
    previewClass: 'from-teal-700 via-emerald-500 to-cyan-400',
    values: {
      '--body': '#f2fbfb',
      '--navbar': '#fbffff',
      '--navbar-border': '#d0e9e8',
      '--card': '#ffffff',
      '--card-foreground': '#0f172a',
      '--popover': '#ffffff',
      '--popover-foreground': '#0f172a',
      '--primary': '#0f766e',
      '--primary-foreground': '#ffffff',
      '--secondary': '#ccfbf1',
      '--secondary-foreground': '#134e4a',
      '--muted': '#99f6e4',
      '--muted-foreground': '#4b5563',
      '--accent': '#5eead4',
      '--accent-foreground': '#134e4a',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#d4e9e6',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#99f6e4',
      '--ring': '#0f766e',
      '--chart-1': '#115e59',
      '--chart-2': '#14b8a6',
      '--chart-3': '#10b981',
      '--chart-4': '#06b6d4',
      '--chart-5': '#3b82f6',
      '--sidebar': '#f6fefe',
      '--sidebar-foreground': '#0f172a',
      '--sidebar-primary': '#0f766e',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#ccfbf1',
      '--sidebar-accent-foreground': '#134e4a',
      '--sidebar-border': '#d0e9e8',
      '--sidebar-ring': '#0f766e',
    },
  },
  {
    key: 'slate',
    name: 'Slate',
    description: 'Neutral graphite blue',
    previewClass: 'from-slate-700 via-slate-600 to-sky-500',
    values: {
      '--body': '#f6f8fb',
      '--navbar': '#ffffff',
      '--navbar-border': '#d7dde6',
      '--card': '#ffffff',
      '--card-foreground': '#111827',
      '--popover': '#ffffff',
      '--popover-foreground': '#111827',
      '--primary': '#334155',
      '--primary-foreground': '#ffffff',
      '--secondary': '#e2e8f0',
      '--secondary-foreground': '#1e293b',
      '--muted': '#cbd5e1',
      '--muted-foreground': '#475569',
      '--accent': '#bfdbfe',
      '--accent-foreground': '#1e3a8a',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#dbe1ea',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#cbd5e1',
      '--ring': '#334155',
      '--chart-1': '#1e293b',
      '--chart-2': '#475569',
      '--chart-3': '#64748b',
      '--chart-4': '#0ea5e9',
      '--chart-5': '#22c55e',
      '--sidebar': '#fafcff',
      '--sidebar-foreground': '#111827',
      '--sidebar-primary': '#334155',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#e2e8f0',
      '--sidebar-accent-foreground': '#1e293b',
      '--sidebar-border': '#d7dde6',
      '--sidebar-ring': '#334155',
    },
  },
  {
    key: 'orchid',
    name: 'Orchid',
    description: 'Lavender and magenta contrast',
    previewClass: 'from-fuchsia-700 via-purple-600 to-indigo-400',
    values: {
      '--body': '#fbf7ff',
      '--navbar': '#fffefe',
      '--navbar-border': '#eadcf4',
      '--card': '#ffffff',
      '--card-foreground': '#111827',
      '--popover': '#ffffff',
      '--popover-foreground': '#111827',
      '--primary': '#9333ea',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f3e8ff',
      '--secondary-foreground': '#6b21a8',
      '--muted': '#e9d5ff',
      '--muted-foreground': '#4b5563',
      '--accent': '#d8b4fe',
      '--accent-foreground': '#6b21a8',
      '--destructive': '#ef4444',
      '--destructive-foreground': '#ffffff',
      '--border': '#eadff2',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#d8b4fe',
      '--ring': '#9333ea',
      '--chart-1': '#7e22ce',
      '--chart-2': '#a855f7',
      '--chart-3': '#c084fc',
      '--chart-4': '#6366f1',
      '--chart-5': '#ec4899',
      '--sidebar': '#fdfaff',
      '--sidebar-foreground': '#111827',
      '--sidebar-primary': '#9333ea',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#f3e8ff',
      '--sidebar-accent-foreground': '#6b21a8',
      '--sidebar-border': '#eadcf4',
      '--sidebar-ring': '#9333ea',
    },
  },
  {
    key: 'cocoa',
    name: 'Cocoa',
    description: 'Earthy brown and cream',
    previewClass: 'from-amber-800 via-orange-700 to-stone-500',
    values: {
      '--body': '#faf7f4',
      '--navbar': '#fffdfb',
      '--navbar-border': '#e7d9ce',
      '--card': '#ffffff',
      '--card-foreground': '#1c1917',
      '--popover': '#ffffff',
      '--popover-foreground': '#1c1917',
      '--primary': '#92400e',
      '--primary-foreground': '#ffffff',
      '--secondary': '#f5e7db',
      '--secondary-foreground': '#78350f',
      '--muted': '#e7d3c3',
      '--muted-foreground': '#57534e',
      '--accent': '#fed7aa',
      '--accent-foreground': '#7c2d12',
      '--destructive': '#dc2626',
      '--destructive-foreground': '#ffffff',
      '--border': '#e7ddd4',
      '--input': 'transparent',
      '--input-background': '#ffffff',
      '--switch-background': '#fdba74',
      '--ring': '#92400e',
      '--chart-1': '#78350f',
      '--chart-2': '#b45309',
      '--chart-3': '#ea580c',
      '--chart-4': '#65a30d',
      '--chart-5': '#14b8a6',
      '--sidebar': '#fdfaf7',
      '--sidebar-foreground': '#1c1917',
      '--sidebar-primary': '#92400e',
      '--sidebar-primary-foreground': '#ffffff',
      '--sidebar-accent': '#f5e7db',
      '--sidebar-accent-foreground': '#78350f',
      '--sidebar-border': '#e7d9ce',
      '--sidebar-ring': '#92400e',
    },
  },
];

export const DEFAULT_BRANCH_THEME_KEY = 'emerald';

export function normalizeBranchThemeKey(key?: string | null): string {
  const normalized = String(key ?? '')
    .trim()
    .toLowerCase();

  if (normalized === 'royale') {
    return 'royal';
  }

  return normalized || DEFAULT_BRANCH_THEME_KEY;
}

export function findBranchTheme(key?: string | null): BranchThemeDefinition {
  const normalizedKey = normalizeBranchThemeKey(key);
  return BRANCH_THEMES.find((theme) => theme.key === normalizedKey) ?? BRANCH_THEMES[0];
}
